[package]
name = "lyra-upgrade-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Tauri interface for Lyra Upgrade"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json.workspace = true
tauri = { version = "2.11.5", features = [] }
lyra-upgrade-protocol = { path = "../protocol" }
lyra-upgrade-service = { path = "../service" }
