window.LYRA_UPGRADE_CATALOGS = {
  "en-US": {
    product:"LYRA OS · UPDATE",title:"Keep your system reliable",idle:"Ready",summary_kicker:"SYSTEM MAINTENANCE",checking:"Check for updates",checking_help:"Review the system before making any change.",check:"Check",confirm:"Confirm update",restart:"Restart now",rollback:"Restore snapshot",keep_current:"Keep current system",rollback_confirm:"Restart after restoring the recovery snapshot?",show_details:"Show details",hide_details:"Hide details",details:"Operation details",copy:"Copy",export:"Export",events:"Events",console:"Zypper console",filter_all:"All",filter_warnings:"Warnings",filter_errors:"Errors",search:"Search details",new_lines:"New lines — return to end",planned:"Update ready",planned_help:"Review the plan before authentication and changes.",downloading:"Downloading packages",snapshotting:"Creating recovery snapshot",applying:"Installing updates",awaiting_reboot:"Restart required",verifying:"Verifying restart",blocked:"Update blocked",completed:"System updated",failed:"Update failed",needs_recovery:"Recovery required",no_cancel:"Do not turn off the computer. This step cannot be cancelled.",packages:"packages",space:"Required space",snapshot:"Recovery snapshot",reboot_yes:"restart required",reboot_no:"no restart required",preview_failed:"The update could not be completed. Review the details.",preview_recovery:"The system can be restored from the recovery snapshot.",phase_Checking:"Checking",phase_Preflight:"Safety checks",phase_Downloading:"Download",phase_Snapshotting:"Snapshot",phase_Applying:"Install",phase_AwaitingReboot:"Restart",phase_VerifyingBoot:"Verify",phase_Completed:"Complete"
  },
  "pt-BR": {
    product:"LYRA OS · ATUALIZAÇÃO",title:"Mantenha o sistema confiável",idle:"Pronto",summary_kicker:"MANUTENÇÃO DO SISTEMA",checking:"Verificar atualizações",checking_help:"Revise o sistema antes de qualquer alteração.",check:"Verificar",confirm:"Confirmar atualização",restart:"Reiniciar agora",rollback:"Restaurar snapshot",keep_current:"Manter sistema atual",rollback_confirm:"Reiniciar após restaurar o snapshot de recuperação?",show_details:"Mostrar detalhes",hide_details:"Ocultar detalhes",details:"Detalhes da operação",copy:"Copiar",export:"Exportar",events:"Eventos",console:"Console do Zypper",filter_all:"Tudo",filter_warnings:"Avisos",filter_errors:"Erros",search:"Buscar nos detalhes",new_lines:"Novas linhas — voltar ao final",planned:"Atualização pronta",planned_help:"Revise o plano antes da autenticação e das alterações.",downloading:"Baixando pacotes",snapshotting:"Criando snapshot de recuperação",applying:"Instalando atualizações",awaiting_reboot:"Reinicialização necessária",verifying:"Verificando reinicialização",blocked:"Atualização bloqueada",completed:"Sistema atualizado",failed:"Falha na atualização",needs_recovery:"Recuperação necessária",no_cancel:"Não desligue o computador. Esta etapa não pode ser cancelada.",packages:"pacotes",space:"Espaço necessário",snapshot:"Snapshot de recuperação",reboot_yes:"reinicialização necessária",reboot_no:"sem reinicialização",preview_failed:"A atualização não pôde ser concluída. Consulte os detalhes.",preview_recovery:"O sistema pode ser restaurado pelo snapshot de recuperação.",phase_Checking:"Verificação",phase_Preflight:"Segurança",phase_Downloading:"Download",phase_Snapshotting:"Snapshot",phase_Applying:"Instalação",phase_AwaitingReboot:"Reinício",phase_VerifyingBoot:"Validação",phase_Completed:"Concluído"
  },
  "es-ES": {
    product:"LYRA OS · ACTUALIZACIÓN",title:"Mantén el sistema fiable",idle:"Listo",summary_kicker:"MANTENIMIENTO DEL SISTEMA",checking:"Buscar actualizaciones",checking_help:"Revisa el sistema antes de realizar cambios.",check:"Buscar",confirm:"Confirmar actualización",restart:"Reiniciar ahora",rollback:"Restaurar instantánea",keep_current:"Mantener sistema actual",rollback_confirm:"¿Reiniciar después de restaurar la instantánea de recuperación?",show_details:"Mostrar detalles",hide_details:"Ocultar detalles",details:"Detalles de la operación",copy:"Copiar",export:"Exportar",events:"Eventos",console:"Consola de Zypper",filter_all:"Todo",filter_warnings:"Avisos",filter_errors:"Errores",search:"Buscar en los detalles",new_lines:"Nuevas líneas — volver al final",planned:"Actualización lista",planned_help:"Revisa el plan antes de autenticar y cambiar el sistema.",downloading:"Descargando paquetes",snapshotting:"Creando instantánea de recuperación",applying:"Instalando actualizaciones",awaiting_reboot:"Es necesario reiniciar",verifying:"Verificando el reinicio",blocked:"Actualización bloqueada",completed:"Sistema actualizado",failed:"Falló la actualización",needs_recovery:"Se requiere recuperación",no_cancel:"No apagues el equipo. Este paso no se puede cancelar.",packages:"paquetes",space:"Espacio necesario",snapshot:"Instantánea de recuperación",reboot_yes:"reinicio necesario",reboot_no:"sin reinicio",preview_failed:"No se pudo completar la actualización. Revisa los detalles.",preview_recovery:"El sistema puede restaurarse desde la instantánea de recuperación.",phase_Checking:"Comprobación",phase_Preflight:"Seguridad",phase_Downloading:"Descarga",phase_Snapshotting:"Instantánea",phase_Applying:"Instalación",phase_AwaitingReboot:"Reinicio",phase_VerifyingBoot:"Verificación",phase_Completed:"Completado"
  }
};
