window.LYRA_UPGRADE_CATALOGS = {
  "en-US": {
    product:"LYRA OS · UPDATE",title:"Keep your system reliable",idle:"Ready",summary_kicker:"SYSTEM MAINTENANCE",checking:"Check for updates",checking_help:"Review the system before making any change.",check:"Check",confirm:"Confirm update",show_details:"Show details",hide_details:"Hide details",details:"Operation details",copy:"Copy",export:"Export",events:"Events",console:"Zypper console",filter_all:"All",filter_warnings:"Warnings",filter_errors:"Errors",search:"Search details",new_lines:"New lines — return to end",planned:"Update ready",planned_help:"Review the plan before authentication and changes.",downloading:"Downloading packages",snapshotting:"Creating recovery snapshot",applying:"Installing updates",awaiting_reboot:"Restart required",completed:"System updated",failed:"Update failed",needs_recovery:"Recovery required",no_cancel:"Do not turn off the computer. This step cannot be cancelled.",packages:"packages",space:"Required space"
  },
  "pt-BR": {
    product:"LYRA OS · ATUALIZAÇÃO",title:"Mantenha o sistema confiável",idle:"Pronto",summary_kicker:"MANUTENÇÃO DO SISTEMA",checking:"Verificar atualizações",checking_help:"Revise o sistema antes de qualquer alteração.",check:"Verificar",confirm:"Confirmar atualização",show_details:"Mostrar detalhes",hide_details:"Ocultar detalhes",details:"Detalhes da operação",copy:"Copiar",export:"Exportar",events:"Eventos",console:"Console do Zypper",filter_all:"Tudo",filter_warnings:"Avisos",filter_errors:"Erros",search:"Buscar nos detalhes",new_lines:"Novas linhas — voltar ao final",planned:"Atualização pronta",planned_help:"Revise o plano antes da autenticação e das alterações.",downloading:"Baixando pacotes",snapshotting:"Criando snapshot de recuperação",applying:"Instalando atualizações",awaiting_reboot:"Reinicialização necessária",completed:"Sistema atualizado",failed:"Falha na atualização",needs_recovery:"Recuperação necessária",no_cancel:"Não desligue o computador. Esta etapa não pode ser cancelada.",packages:"pacotes",space:"Espaço necessário"
  },
  "es-ES": {
    product:"LYRA OS · ACTUALIZACIÓN",title:"Mantén el sistema fiable",idle:"Listo",summary_kicker:"MANTENIMIENTO DEL SISTEMA",checking:"Buscar actualizaciones",checking_help:"Revisa el sistema antes de realizar cambios.",check:"Buscar",confirm:"Confirmar actualización",show_details:"Mostrar detalles",hide_details:"Ocultar detalles",details:"Detalles de la operación",copy:"Copiar",export:"Exportar",events:"Eventos",console:"Consola de Zypper",filter_all:"Todo",filter_warnings:"Avisos",filter_errors:"Errores",search:"Buscar en los detalles",new_lines:"Nuevas líneas — volver al final",planned:"Actualización lista",planned_help:"Revisa el plan antes de autenticar y cambiar el sistema.",downloading:"Descargando paquetes",snapshotting:"Creando instantánea de recuperación",applying:"Instalando actualizaciones",awaiting_reboot:"Es necesario reiniciar",completed:"Sistema actualizado",failed:"Falló la actualización",needs_recovery:"Se requiere recuperación",no_cancel:"No apagues el equipo. Este paso no se puede cancelar.",packages:"paquetes",space:"Espacio necesario"
  }
};
